# Server Port
server.port=8816

# Application Name
spring.application.name=promotion-service

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=product_promotions;
spring.datasource.username=sa
spring.datasource.password=Test1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.hibernate.ddl-auto=update